project_id = "pldlmtuxqxszaajxtufx"

[functions.notify-club-request]
verify_jwt = false

[functions.notify-club-approved]
verify_jwt = false

[functions.map-processing-webhook]
verify_jwt = false

[functions.trigger-map-processing]
verify_jwt = true

[functions.public-config]
verify_jwt = false
